import type { Metadata } from 'next'
import './css/globals.css'
import Header from '@/components/Header'
import Layout from '@/components/Layout'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Layout>
          <Header/>
          {children}
          <Footer/>
        </Layout>
      </body>
    </html>
  )
}
